# Repositories Configuration
repos:
  - id: /.*/  # सभी repositories को allow किया गया
    branch: /.*/  # सभी branches को allow किया गया

    repo_config_file: atlantis.yaml  # Default repo config file

    plan_requirements: [approved, mergeable, undiverged]
    apply_requirements: [approved, mergeable, undiverged]
    import_requirements: [approved, mergeable, undiverged]

    workflow: windows-workflow  # Custom workflow (नीचे defined है)

    allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge, repo_locking, repo_locks, custom_policy_check]
    allowed_workflows: [windows-workflow]
    allow_custom_workflows: true

    delete_source_branch_on_merge: true
    repo_locking: true
    repo_locks:
      mode: on_plan

    custom_policy_check: false

    pre_workflow_hooks:
      - run: |
          powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "& {
            Start-Process -NoNewWindow -FilePath 'C:\Users\SharkOps011\Downloads\terraform_1.11.0_windows_386\terraform.exe' -ArgumentList 'version'
          }"

    post_workflow_hooks:
      - run: echo "Workflow Execution Completed!"

    policy_check: false

    autodiscover:
      mode: auto
      ignore_paths:
        - foo/*

# Workflows Configuration
workflows:
  windows-workflow:
    plan:
      steps:
        - run: |
            powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "& {
              Start-Process -NoNewWindow -FilePath 'C:\Users\SharkOps011\Downloads\terraform_1.11.0_windows_386\terraform.exe' -ArgumentList 'init', '-input=false', '-upgrade'
            }"
        - run: |
            powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "& {
              Start-Process -NoNewWindow -FilePath 'C:\Users\SharkOps011\Downloads\terraform_1.11.0_windows_386\terraform.exe' -ArgumentList 'plan'
            }"
    apply:
      steps:
        - run: |
            powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "& {
              Start-Process -NoNewWindow -FilePath 'C:\Users\SharkOps011\Downloads\terraform_1.11.0_windows_386\terraform.exe' -ArgumentList 'apply', '-auto-approve'
            }"
