repos:
  - id: "github.com/sonakshi-devops/terraform-atlantis"
    allowed_overrides: [workflow]
    allow_custom_workflows: true
    apply_requirements: [approved]
    pre_workflow_hooks:
      - run: |
          powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "& {
            & \"C:\\Users\\SharkOps011\\Downloads\\terraform_1.11.0_windows_386\\terraform.exe\" version
          }"
        description: "Check Terraform Version"
    workflow: "windows-workflow"

workflows:
  windows-workflow:
    plan:
      steps:
        - run: |
            powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "& {
              & \"C:\\Users\\SharkOps011\\Downloads\\terraform_1.11.0_windows_386\\terraform.exe\" init -input=false -upgrade
              & \"C:\\Users\\SharkOps011\\Downloads\\terraform_1.11.0_windows_386\\terraform.exe\" plan
            }"
    apply:
      steps:
        - run: |
            powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "& {
              & \"C:\\Users\\SharkOps011\\Downloads\\terraform_1.11.0_windows_386\\terraform.exe\" apply -auto-approve
            }"
