repos:
  - id: "github.com/sonakshi-devops/terraform-atlantis"  # Specify your GitHub repository
    workflows:
      windows-workflow:
        plan:
          steps:
            - run: "powershell.exe -ExecutionPolicy Bypass -NoProfile -Command \"& { 'C:\\path\\to\\terraform.exe' plan }\""
        apply:
          steps:
            - run: "powershell.exe -ExecutionPolicy Bypass -NoProfile -Command \"& { 'C:\\path\\to\\terraform.exe' apply -auto-approve }\""

workflows:
  windows-workflow:
    plan:
      steps:
        - run: |
            powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "& {
              'C:\Users\SharkOps011\Downloads\terraform_1.11.0_windows_386\terraform.exe' init -input=false -upgrade
              'C:\Users\SharkOps011\Downloads\terraform_1.11.0_windows_386\terraform.exe' plan
            }"
    apply:
      steps:
        - run: |
            powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "& {
              'C:\Users\SharkOps011\Downloads\terraform_1.11.0_windows_386\terraform.exe' apply -auto-approve
            }"

projects:
  - name: terraform-setup-project
    dir: "terraform-atlantis"  # Directory where your Terraform files are located
    workflow: windows-workflow
    autoplan:
      when_modified: ["*.tf", "*.tfvars"]
      enabled: true
